### ISSUE TITLE
Feature Request: add the possibility to load data from a standard JSON file

### ISSUE THREAD

**Issue by DPorcheron** [tinesoft/spring-esdata-loader#5]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
It would be a real improvement to give the possibility to load data from a standard JSON file in addition to a JSON stream file (as it's already the case). 
It would be more human readable and easier to add data for test purposes.

What do you think abouth that @tinesoft ?

**Comment by tinesoft** [comment]
Hi David,

What do you mean by "standard json file"?
You can already load data from a regular `*.json` file or a gzip-compressed json file (`*.json.gz`)...

**Comment by DPorcheron** [comment]
Hi,

I thought more about the format in the json file.
What I propose it's to allow a json format like : 
```
[
  {
     "id": 1,
     "name": "toto"
  },
  {
     "id": 2,
     "name": "titi"
  }
]
```
in addition to the json stream (json line by line).
Cause in most cases we want to have human readable test data which can be easily modified for future modifications in tests.
Moreover, with this format we could avoid metadata like index name or index type, which is not relevant in data test, and we could pass it to `@LoadEsData` for example.

It would cause a little refactoring but I think it would be a real enhancement.

**Comment by tinesoft** [comment]
Hi @DPorcheron ,

Now i understand what you mean. It is indeed a valid request👍 .
In my original usecase, i already had a lot of existing data into my ES. So a dump was quick and easy!

To implement this, i'm thinking about adding an extra property in the `LoadEsData(Rule|Extension)`, called  **esDataFormat** (enumeration), which will have the following values:
* **DUMP** :  the current format, when data are dumped from ES using tools like `elasticdump`
* **MANUAL** (not sure about the name yet...) : handwritten data, as an array of json objects

When unspecified, the tool will try to detect it from the json file, and fail if it cannot.

Data will be loaded accorded to that format.

What do you think?

**Comment by DPorcheron** [comment]
Hi @tinesoft,

I'm ok with you for the implementation using a specific enum 👍 

To simplify the auto detection of the mode, I think that in **MANUAL** mode the tool should force the format with a JSON array. 

So if we have a start character like `[` it's the **MANUAL** mode and if we have `{` it's the **DUMP** mode.

And even if we have only one element in **MANUAL** mode, we would have to specify an array, but I think it's not a bad thing for test purposes.

**Comment by tinesoft** [comment]
Agreed.

I will start looking at this shortly, it shouldn't take too long to implement.
Stay tuned!
